[package]
name = "nixie_client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
defmt-decoder = "1.1.0"
eframe = { version = "0.36.1", features = ["persistence"] }
egui = "0.36.1"
egui_extras = "0.36.1"
nixie-wire = { version = "0.1.0", path = "../wire" }
postcard = "1.1.3"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = [
    "rt",
    "net",
    "time",
    "sync",
    "io-util",
    "macros",
] }
