#![cfg_attr(not(test), no_std)]

use serde::Deserialize;
use serde::Serialize;

/// Exchanged in handshake frames
pub const PROTOCOL_VERSION: u16 = 1;

/// Upper bound on the size of one encoded defmt frame
pub const MAX_LOG_FRAME_SIZE: u16 = 256;

pub const FRAME_HEADER_SIZE: usize = 2;

/// Device TCTM listens on this port
pub const TCTM_PORT: u16 = 2718;

/// Current worst case is Telemetry::Log at 269 bytes encoded, rounded up to 512 to give ourselves a
/// fighting chance when we forget to update this.
pub const MAX_MESSAGE_SIZE: usize = 512;
const _: () = assert!(MAX_MESSAGE_SIZE >= MAX_LOG_FRAME_SIZE as usize + 13);

pub const MAX_FRAME_SIZE: usize = FRAME_HEADER_SIZE + MAX_MESSAGE_SIZE;

/// A command is any payload sent to the device.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Command {
    Init { version: u16 },
    Reset,
}

/// A message sent to the device. Contains a command and a sequence number generated by the host.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ToDevice {
    /// The command sequence number. Increments once per command sent.
    sequence: u32,

    payload: Command,
}

impl ToDevice {
    pub fn new(sequence: u32, payload: Command) -> ToDevice {
        ToDevice { sequence, payload }
    }

    pub fn sequence(&self) -> u32 {
        self.sequence
    }

    pub fn payload(&self) -> Command {
        self.payload
    }
}

/// Telemetry is any payload sent to the host.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Telemetry<'a> {
    InitAck {
        version: u16,
        firmware_id: &'a str,
        built: &'a str,
    },
    /// Sent in reply to commands that generate no other telemetry. The wrapping packet carries the
    /// updated sequence number.
    Ack,
    Log {
        /// The log frame number. Incremented by the device for each log frame generated. Skipped
        /// numbers indicate dropped frames.
        sequence: u32,

        /// defmt frame data
        frame: &'a [u8],
    },
}

/// A message sent by the device. Contains an sequence number that acks the last command seen and a
/// telemetry payload.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ToHost<'a> {
    /// The highest sequence number received in a command.
    sequence: u32,

    #[serde(borrow)]
    payload: Telemetry<'a>,
}

impl<'a> ToHost<'a> {
    pub fn new(sequence: u32, payload: Telemetry<'a>) -> ToHost<'a> {
        ToHost { sequence, payload }
    }

    pub fn sequence(&self) -> u32 {
        self.sequence
    }

    pub fn payload(&self) -> Telemetry<'a> {
        self.payload
    }
}

/// Copies a packet to the given buffer, prepending its length.
pub fn encode<'a, T: Serialize>(
    msg: &T,
    buffer: &'a mut [u8],
) -> Result<&'a mut [u8], postcard::Error> {
    if buffer.len() < FRAME_HEADER_SIZE {
        return Err(postcard::Error::SerializeBufferFull);
    }
    let end = buffer.len().min(MAX_FRAME_SIZE);
    let len = postcard::to_slice(msg, &mut buffer[FRAME_HEADER_SIZE..end])?.len();
    buffer[..FRAME_HEADER_SIZE].copy_from_slice(&u16::to_le_bytes(len as u16));
    Ok(&mut buffer[..(FRAME_HEADER_SIZE + len)])
}

/// Gets the length of a packet
pub fn payload_len(header: [u8; FRAME_HEADER_SIZE]) -> Option<usize> {
    let len = usize::from(u16::from_le_bytes(header));
    if len == 0 || len > MAX_MESSAGE_SIZE {
        None
    } else {
        Some(len)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wire_format_is_stable() {
        let mut buf = [0u8; 64];

        let bytes: &[u8] = postcard::to_slice(&Command::Init { version: 1 }, &mut buf).unwrap();
        assert_eq!(bytes, &[0x00, 0x01][..]);

        let msg = ToDevice {
            sequence: 1,
            payload: Command::Reset,
        };
        let bytes: &[u8] = postcard::to_slice(&msg, &mut buf).unwrap();
        assert_eq!(bytes, &[0x01, 0x01][..]);

        let msg = ToHost {
            sequence: 2,

            payload: Telemetry::Log {
                sequence: 10,
                frame: &[0xAA, 0x00],
            },
        };
        let bytes: &[u8] = postcard::to_slice(&msg, &mut buf).unwrap();
        assert_eq!(bytes, &[0x02, 0x02, 0x0A, 0x02, 0xAA, 0x00][..]);
    }

    #[test]
    fn log_roundtrips_borrowed() {
        let mut buf = [0u8; 64];
        let sent = ToHost {
            sequence: 7,

            payload: Telemetry::Log {
                sequence: 10,
                frame: &[1, 2, 3],
            },
        };
        let bytes = postcard::to_slice(&sent, &mut buf).unwrap();
        let got: ToHost = postcard::from_bytes(bytes).unwrap();
        assert_eq!(got, sent);
    }

    #[test]
    fn encode_prepends_little_endian_length() {
        let msg = ToHost {
            sequence: 2,
            payload: Telemetry::Log {
                sequence: 10,
                frame: &[0xAA, 0x00],
            },
        };
        let mut buf = [0u8; 64];
        let frame = encode(&msg, &mut buf).unwrap();
        assert_eq!(frame, &[0x06, 0x00, 0x02, 0x02, 0x0A, 0x02, 0xAA, 0x00][..]);

        let header: [u8; FRAME_HEADER_SIZE] = frame[..FRAME_HEADER_SIZE].try_into().unwrap();
        let len = payload_len(header).unwrap();
        let got: ToHost = postcard::from_bytes(&frame[FRAME_HEADER_SIZE..][..len]).unwrap();
        assert_eq!(got, msg);
    }

    #[test]
    fn encode_rejects_oversize_and_undersize() {
        // A frame larger than MAX_MESSAGE_SIZE must fail even when the caller's buffer would hold it.
        let big = [0u8; MAX_MESSAGE_SIZE];
        let msg = ToHost {
            sequence: 1,
            payload: Telemetry::Log {
                sequence: 1,
                frame: &big,
            },
        };
        let mut roomy = [0u8; 2 * MAX_FRAME_SIZE];
        assert!(encode(&msg, &mut roomy).is_err());

        // A buffer that cannot hold the header must fail instead of panicking.
        let mut tiny = [0u8; FRAME_HEADER_SIZE - 1];
        assert!(encode(&Command::Reset, &mut tiny).is_err());
    }

    #[test]
    fn payload_len_rejects_zero_and_oversize() {
        assert_eq!(payload_len([0x06, 0x00]), Some(6));
        assert_eq!(payload_len([0x00, 0x02]), Some(MAX_MESSAGE_SIZE));
        assert_eq!(payload_len([0x00, 0x00]), None);
        assert_eq!(payload_len([0x01, 0x02]), None);
    }
}
