#![cfg_attr(not(test), no_std)]

use serde::Deserialize;
use serde::Serialize;

/// Exchanged in handshake frames
pub const PROTOCOL_VERSION: u16 = 1;

/// Upper bound on the size of one encoded defmt frame
pub const MAX_LOG_FRAME_SIZE: u16 = 256;

/// Device TCTM listens on this port
pub const TCTM_PORT: u16 = 2718;

/// Current worst case is Telemetry::Log at 269 bytes encoded, rounded up to 512 to give ourselves a
/// fighting chance when we forget to update this.
pub const MAX_MESSAGE_SIZE: usize = 512;
const _: () = assert!(MAX_MESSAGE_SIZE >= MAX_LOG_FRAME_SIZE as usize + 13);

/// A command is any payload sent to the device.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Command {
    Init { version: u16 },
    Reset,
}

/// A message sent to the device. Contains a command and a sequence number generated by the host.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ToDevice {
    /// The command sequence number. Increments once per command sent.
    sequence: u32,

    payload: Command,
}

impl ToDevice {
    pub fn new(sequence: u32, payload: Command) -> ToDevice {
        ToDevice { sequence, payload }
    }

    pub fn sequence(&self) -> u32 {
        self.sequence
    }

    pub fn payload(&self) -> Command {
        self.payload
    }
}

/// Telemetry is any payload sent to the host.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Telemetry<'a> {
    InitAck {
        version: u16,
    },
    /// Sent in reply to commands that generate no other telemetry. The wrapping packet carries the
    /// updated sequence number.
    Ack,
    Log {
        /// The log frame number. Incremented by the device for each log frame generated. Skipped
        /// numbers indicate dropped frames.
        sequence: u32,

        /// defmt frame data
        frame: &'a [u8],
    },
}

/// A message sent by the device. Contains an sequence number that acks the last command seen and a
/// telemetry payload.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ToHost<'a> {
    /// The highest sequence number received in a command.
    sequence: u32,

    #[serde(borrow)]
    payload: Telemetry<'a>,
}

impl<'a> ToHost<'a> {
    pub fn new(sequence: u32, payload: Telemetry<'a>) -> ToHost<'a> {
        ToHost { sequence, payload }
    }

    pub fn sequence(&self) -> u32 {
        self.sequence
    }

    pub fn payload(&self) -> Telemetry<'a> {
        self.payload
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wire_format_is_stable() {
        let mut buf = [0u8; 64];

        let bytes: &[u8] = postcard::to_slice(&Command::Init { version: 1 }, &mut buf).unwrap();
        assert_eq!(bytes, &[0x00, 0x01][..]);

        let msg = ToDevice {
            sequence: 1,
            payload: Command::Reset,
        };
        let bytes: &[u8] = postcard::to_slice(&msg, &mut buf).unwrap();
        assert_eq!(bytes, &[0x01, 0x01][..]);

        let msg = ToHost {
            sequence: 2,

            payload: Telemetry::Log {
                sequence: 10,
                frame: &[0xAA, 0x00],
            },
        };
        let bytes: &[u8] = postcard::to_slice(&msg, &mut buf).unwrap();
        assert_eq!(bytes, &[0x02, 0x02, 0x0A, 0x02, 0xAA, 0x00][..]);
    }

    #[test]
    fn log_roundtrips_borrowed() {
        let mut buf = [0u8; 64];
        let sent = ToHost {
            sequence: 7,

            payload: Telemetry::Log {
                sequence: 10,
                frame: &[1, 2, 3],
            },
        };
        let bytes = postcard::to_slice(&sent, &mut buf).unwrap();
        let got: ToHost = postcard::from_bytes(bytes).unwrap();
        assert_eq!(got, sent);
    }
}
